package app

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/png"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"sync/atomic"
	"testing"

	"denova/config"
	booklore "denova/internal/book/lore"
	"denova/internal/platform"
	"denova/internal/project"
)

func TestPlatformResourcesReuseScopedLibraryAndImageProvider(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	var imageData bytes.Buffer
	if err := png.Encode(&imageData, image.NewRGBA(image.Rect(0, 0, 2, 2))); err != nil {
		t.Fatal(err)
	}
	var calls atomic.Int32
	provider := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		var input struct {
			Model  string `json:"model"`
			Prompt string `json:"prompt"`
			N      int    `json:"n"`
		}
		if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
			t.Error(err)
		}
		if r.URL.Path != "/v1/images/generations" || r.Header.Get("Authorization") != "Bearer test-resource-secret" || input.Model != "test-image-model" || input.Prompt != "A quiet station" || input.N != 1 {
			t.Errorf("unexpected image provider request: %s %#v", r.URL.Path, input)
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": []any{map[string]string{"b64_json": base64.StdEncoding.EncodeToString(imageData.Bytes()), "revised_prompt": "Quiet station"}}})
	}))
	defer provider.Close()
	if err := config.WriteSettingsFile(config.UserConfigPath(root), config.Settings{
		ImageAPIEndpoints: []config.ImageAPIEndpointSettings{{ID: "test-images", Provider: config.ImageProviderOpenAI, Protocol: config.ImageProtocolOpenAI, APIKey: "test-resource-secret", BaseURL: provider.URL + "/v1"}},
		ImageAPIProfiles:  []config.ImageAPIProfileSettings{{ID: "illustrator", EndpointID: "test-images", Model: "test-image-model"}},
	}); err != nil {
		t.Fatal(err)
	}
	application, err := New(ctx, &config.Config{
		DenovaDir: root, OpenAIModel: "test-text-model",
	})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(application.Close)
	projects := []project.Record{}
	for _, name := range []string{"first", "second"} {
		directory := filepath.Join(root, "projects", name)
		if err := os.MkdirAll(directory, 0700); err != nil {
			t.Fatal(err)
		}
		record, err := application.projectRegistry.Add(directory, project.TypeGeneral, name)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := application.projectRegistry.EnsureStore(record); err != nil {
			t.Fatal(err)
		}
		projects = append(projects, record)
		store := booklore.NewStore(directory)
		if _, err := store.Create(booklore.ItemInput{ID: name, Name: name, Type: "character", Content: "The " + name + " character", Image: &booklore.Image{ImagePath: "assets/portrait.png"}}); err != nil {
			t.Fatal(err)
		}
		if err := os.MkdirAll(filepath.Join(directory, "assets"), 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(directory, "assets", "portrait.png"), imageData.Bytes(), 0600); err != nil {
			t.Fatal(err)
		}
	}
	host := platformResourceHost{app: application}
	items, err := host.LibraryItems(ctx, projects[1].ID)
	if err != nil || len(items) != 1 || items[0].Name != "second" || items[0].Image == nil || items[0].Image.Path != "assets/portrait.png" {
		t.Fatalf("scoped library: %#v %v", items, err)
	}
	data, err := host.ReadAsset(ctx, projects[1].ID, "assets/portrait.png")
	if err != nil || !bytes.Equal(data, imageData.Bytes()) {
		t.Fatalf("scoped asset: %v", err)
	}
	if _, err := host.ReadAsset(ctx, projects[1].ID, "../first/assets/portrait.png"); err == nil {
		t.Fatal("cross-Project asset traversal succeeded")
	}
	if _, err := host.LibraryItems(ctx, "unknown-project"); err == nil {
		t.Fatal("unknown Project library succeeded")
	}
	generated, err := host.GenerateImage(ctx, projects[1].ID, "illustrator", platform.ImageRequest{CommandID: "scene-1", ModelSlot: "art", Prompt: "A quiet station"})
	if err != nil || !bytes.Equal(generated.Data, imageData.Bytes()) || generated.RevisedPrompt != "Quiet station" || calls.Load() != 1 {
		t.Fatalf("image provider: %#v calls=%d err=%v", generated, calls.Load(), err)
	}
	// Generated bytes return to platform-owned scope storage; source assets and
	// library bindings remain untouched, including General Projects.
	items, err = host.LibraryItems(ctx, projects[1].ID)
	if err != nil || items[0].Image.Path != "assets/portrait.png" {
		t.Fatalf("generation changed library: %#v %v", items, err)
	}
}
