import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import { NativeTitleTooltip } from './native-title-tooltip'
import { TooltipProvider } from '@/components/ui/tooltip'

function renderTooltip(content: React.ReactNode, pointerDelayMs = 0) {
  return render(
    <TooltipProvider delayDuration={0}>
      <NativeTitleTooltip pointerDelayMs={pointerDelayMs} />
      {content}
    </TooltipProvider>,
  )
}

describe('NativeTitleTooltip', () => {
  it('replaces a native pointer title with the shared tooltip and restores it on leave', async () => {
    renderTooltip(<button title="Open details">Details</button>)
    const button = screen.getByRole('button', { name: 'Details' })

    fireEvent.pointerOver(button, { pointerType: 'mouse' })

    expect(button).not.toHaveAttribute('title')
    expect(await screen.findByRole('tooltip')).toHaveTextContent('Open details')

    fireEvent.pointerOut(button, { pointerType: 'mouse', relatedTarget: document.body })

    await waitFor(() => expect(screen.queryByRole('tooltip')).not.toBeInTheDocument())
    expect(button).toHaveAttribute('title', 'Open details')
  })

  it('shows keyboard-focused titles immediately and preserves multiline content', async () => {
    renderTooltip(<button title={'Branch name\nBranch summary'}>Branch</button>)
    const button = screen.getByRole('button', { name: 'Branch' })

    fireEvent.keyDown(document, { key: 'Tab' })
    fireEvent.focusIn(button)

    expect(await screen.findByRole('tooltip')).toHaveTextContent('Branch name Branch summary')
    expect(button).toHaveAttribute('title', 'Branch name\nBranch summary')

    fireEvent.focusOut(button, { relatedTarget: document.body })
    expect(button).toHaveAttribute('title', 'Branch name\nBranch summary')
  })

  it('does not treat pointer-driven focus or menu focus restoration as keyboard focus', async () => {
    renderTooltip(
      <>
        <button title="More actions">More</button>
        <div data-testid="menu">Menu</div>
      </>,
      80,
    )
    const button = screen.getByRole('button', { name: 'More' })
    const menu = screen.getByTestId('menu')

    fireEvent.pointerOver(button, { pointerType: 'mouse' })
    fireEvent.pointerDown(button, { pointerType: 'mouse' })
    fireEvent.focusIn(button)
    expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()

    fireEvent.pointerOut(button, { pointerType: 'mouse', relatedTarget: menu })
    fireEvent.focusOut(button, { relatedTarget: menu })
    fireEvent.focusIn(button)

    await new Promise((resolve) => setTimeout(resolve, 100))
    expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
    expect(button).toHaveAttribute('title', 'More actions')
  })

  it('waits for a stable pointer hover before opening', async () => {
    renderTooltip(<button title="Delayed hint">Hover</button>, 80)
    const button = screen.getByRole('button', { name: 'Hover' })

    fireEvent.pointerOver(button, { pointerType: 'mouse' })

    expect(button).not.toHaveAttribute('title')
    expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
    expect(await screen.findByRole('tooltip')).toHaveTextContent('Delayed hint')
  })

  it('ignores touch hover and the focus generated by a tap', () => {
    renderTooltip(<button title="Touch action">Action</button>)
    const button = screen.getByRole('button', { name: 'Action' })

    fireEvent.pointerDown(button, { pointerType: 'touch' })
    fireEvent.pointerOver(button, { pointerType: 'touch' })
    fireEvent.focusIn(button)

    expect(screen.queryByRole('tooltip')).not.toBeInTheDocument()
    expect(button).toHaveAttribute('title', 'Touch action')
  })
})
